# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Blessing/Blasphemy Uber Priest"
description: > # this means to ignore newlines until "email:"
   The first machilne learning mood swinger, Geekcon 2017 project

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/hand.png"
float_logo: true # true, false (default)
permalink: :title

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Blessing/Blasphemy uber priest'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	15

# by zohar sacks
# url: "http://myblog.***.***" # the base hostname & protocol for your site
# baseurl: ""
# #used to display twitter cards
# twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
# disqus: open-amdocs

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/search?q=%23geekcon
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  
  - icon:	facebook
    url:	https://facebook.com/Geekcon-233690200016637
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="
